# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28a8bf18075943652b36527fc960fe290ea4410de7457cc5d7c18c8e7f7d57a623f9ae1834d8878abbb58f3b3847f633685305b2c1eec5aab17f18d66a77a067

test:
  secret_key_base: b72d0a2cdc8ed2fa15613889b11e12077f98031acfb027524d62700bbc9ceef36dea9b277344be6824308d78d0c14335f83dafb6e3dd8e1c288e5159ddaac94e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
